[build]
    command   = "yarn run build:serverless"
    functions = "out_functions"
    publish   = "out_publish"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"

[context.server.environment]
NEXT_SERVERLESS = "false"
NODE_ENV = "production"